### ISSUE TITLE
run bpanel on server

### ISSUE THREAD

**Issue by micahstubbs** [micahstubbs/c4yt#13]
encountered this error

when I run `npm run start:dev`

```
➜  bpanel git:(c4yt) ✗ npm run start:dev                                                                                    [111/154]

> bpanel@0.0.1-rc1 start:dev /root/workspace/bpanel
> node server --dev

info: bsock running on port 8000
info: bpanel app running on port 5000
error: uncaughtException: Network error: ws://127.0.0.1:18556/socket.io/?transport=websocket: connect ECONNREFUSED 127.0.0.1:18556 da
te=Sun Apr 08 2018 19:23:45 GMT+0000 (UTC), pid=23025, uid=0, gid=0, cwd=/root/workspace/bpanel, execPath=/usr/bin/node, version=v8.$
1.1, argv=[/usr/bin/node, /root/workspace/bpanel/server/index.js, --watch], rss=50917376, heapTotal=32325632, heapUsed=12621336, ext$
rnal=322401, loadavg=[0.24462890625, 0.09765625, 0.02880859375], uptime=68451, trace=[column=24, file=/root/workspace/bpanel/node_mo$
ules/bsock/lib/socket.js, function=Socket.onError, line=245, method=onError, native=false, column=18, file=/root/workspace/bpanel/no$
e_modules/bsock/lib/socket.js, function=Client.ws.onerror, line=174, method=onerror, native=false, column=30, file=/root/workspace/b$
anel/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js, function=Client.dispatchEvent, line=22, method=dispatchEven$
, native=false, column=10, file=/root/workspace/bpanel/node_modules/faye-websocket/lib/faye/websocket/api.js, function=Client._emitE$
ror, line=158, method=_emitError, native=false, column=12, file=/root/workspace/bpanel/node_modules/faye-websocket/lib/faye/websocke$
/api.js, function=null, line=127, method=null, native=false, column=20, file=events.js, function=emitOne, line=121, method=null, nat$
ve=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destr$
y.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTic$
Callback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=18$
, method=_tickCallback, native=false], stack=[Error: Network error: ws://127.0.0.1:18556/socket.io/?transport=websocket: connect ECO$
NREFUSED 127.0.0.1:18556,     at Socket.onError (/root/workspace/bpanel/node_modules/bsock/lib/socket.js:245:24),     at Client.ws.o$
error (/root/workspace/bpanel/node_modules/bsock/lib/socket.js:174:18),     at Client.dispatchEvent (/root/workspace/bpanel/node_mod$
les/faye-websocket/lib/faye/websocket/api/event_target.js:22:30),     at Client._emitError (/root/workspace/bpanel/node_modules/faye$
websocket/lib/faye/websocket/api.js:158:10),     at Socket.<anonymous> (/root/workspace/bpanel/node_modules/faye-websocket/lib/faye/$
ebsocket/api.js:127:12),     at emitOne (events.js:121:20),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/strea$
s/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/proc$
ss/next_tick.js:180:9)]
```

**Comment by micahstubbs** [comment]
```
Module build failed: Error: Missing binding /root/workspace/bpanel/node_modules/node-sass/vendor/linux-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x
```

**Comment by micahstubbs** [comment]
`sudo npm install --unsafe-perm -g node-sass`

appears to be a solution

https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#cannot-find-module-rootinstalljs

**Comment by micahstubbs** [comment]
will try this as well

`sudo npm install --unsafe-perm -g babel-node`

**Comment by micahstubbs** [comment]
ok, that didn't work either.  will pause here for now.

**Comment by micahstubbs** [comment]
`npm rebuild node-sass --force` trying this now

**Comment by micahstubbs** [comment]
ok, trying this now in response to an error message

`bcoin@git+https://github.com/bcoin-org/bcoin.git#wallet-rewrite`

**Comment by micahstubbs** [comment]
trying this out now 

`npm install --save-dev @babel/node`

**Comment by micahstubbs** [comment]
hhmmmm that didn't work 🤔
